version: '3'
volumes:
    dados: 
networks: 
    banco:
    web:  
    fila:              
services: 
    db:
        image: postgres:12.4
        environment: 
            - POSTGRES_PASSWORD="postgres"
        volumes: 
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql 
        networks: 
            - banco    
    frontend:
        image: nginx:1.19.2
        volumes: 
            # site
            - ./web:/usr/share/nginx/html/
            # Configuracao do Proxy reverso
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 80:80
        networks: 
            - web
        depends_on: 
            - app        
    app:
        image: python:3.6
        volumes: 
            # Aplicacao
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        ports:
            - 8081:8081
        networks: 
            - banco
            - web
            - fila
        depends_on: 
            - db 
            - queue
        environment: 
            - DB_NAME=abc_sender    
    queue:
        image: redis:3.2
        networks:
            - fila        
    worker:
        #image: python:3.6
        build: worker
        volumes:
            # Worker
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        #command: bash ./app.sh
        networks:
            - fila
        depends_on:
            - queue   


